src/api/api.js
src/components/common/ToggleList.jsx

[Feat]my page FAQ 하위요소 추가 #2

---

package-lock.json
package.json
src/App.jsx
src/components/common/BottomNav.jsx
src/recoil/atoms.jsx

- 접속시 메인으로 변경
- 로그인 유무에 따른 네비바 아이콘 연결(로그인 유무 리코일로 상태관리)
closed: #32

[Feat]접속시 mainpage 연결/url 리다이렉션 #32

---

src/api/api.js
src/components/common/card/CompanyCard.jsx
src/pages/mainpage/CompanySection.jsx
src/pages/mainpage/Main.jsx

- 요즘뜨는 키워드 , 추천학습 영상, 관심 회사 api 연동 완료
- 관심회사 이미지 오류 확인필요
-
closed: #34

[feat] 메인화면 hotskills, 추천영상, 관심있는 회사 api 연동 완료

---

package.json
src/App.jsx
src/api/api.js
src/components/common/navigation-btn/NavigationBtn.jsx
src/components/common/new-btn/NewBtn.jsx
src/components/common/new-daypicker/NewDayPicker.jsx
src/components/common/new-input/NewInput.jsx
src/components/common/total-input-form/TotalInputForm.jsx
src/pages/coffeechat/Coffee.jsx
src/pages/info/InFo.jsx
src/pages/info/InFoBasic.jsx
src/pages/info/InfoJD.jsx
src/pages/info/InfoSkill.jsx
src/pages/info/InfoStyles.js
src/pages/mainpage/Main.jsx
src/pages/sign-in/KakaoLoginBtn.jsx
src/pages/sign-in/KakaoRedirectPage.jsx
src/recoil/atoms.jsx

- 카카오톡 로그인 리다이랙트 연결 (회원일 때는 미고려)
-  userInfo recoil 전역변수로 재구성
- helperText, 중복 선택 로직 구현 (디테일은 미구현)
- 버튼, 텍스트박스 등의 전반적 스타일 수정

Feat/user login/#40

---

src/components/common/swipe/SwipJobSkill.jsx

[style] 마이페이지 정보수정 화면 직무선택 스타일 변경

---

src/App.jsx
src/api/api.js
src/components/common/card/CoffeeChatCard.jsx
src/pages/FavoritesVideo.jsx
src/pages/MyCoffeeChat.jsx
src/pages/MyPage.jsx

- mypage 커피챗 화면 디자인
- 커피챗 api 연동(내가 오픈한, 신청한)
- 페이지네이션 컴포넌트 api 연동
closed: #56

[Feat]my page의coffee chat화면 기능 및 디자인 #56

---

src/components/common/ToggleList.jsx
src/components/common/swipe/SwipJobSkill.jsx
src/pages/InfoEdit.jsx
src/pages/MyPage.jsx

- 마이페이지, 정보수정 페이지
- 디자인 수정
- 공통컴포넌트화

🔨 Modify:  디자인 수정, 공통컴포넌트화

---

src/api/api.js
src/pages/MyCoffeeChat.jsx

- 통신데이터 없을때의 화면 제작
closed: #56

[style] 통신데이터가없을때의 안내메시지와 레이아웃 수정_#56

---

src/components/common/BottomNav.jsx
src/pages/coffeechat/Coffee.jsx
src/pages/info/InFo.jsx
src/pages/mainpage/Main.jsx
src/pages/sign-in/KakaoRedirectPage.jsx

- 로그인 상태 저장
- 로그인 상태 저장 , 로그인에 따른 nav 수정

✨ Feat :  로그인 상태 저장 , 로그인에 따른 nav 수정

---

src/components/common/new-daypicker/NewDayPicker.jsx
src/components/common/new-input/NewInput.jsx
src/pages/coffeechat/CoffeeOpen.jsx

- meetDate 양식 수정
-  날짜+시간으로 받기 조건 추가
- 만약 daytime 속성이 true 일 경우 => DateTimePicke 사용
- false일 경우 DatePicker 사용

✨ Feat :  meetDate을 일시와 시간을 받기

---

src/api/api.js
src/components/common/card/CoffeeChatCard.jsx
src/components/common/filters/Filters.jsx
src/pages/coffeechat/Coffee.jsx

- hover 애니메이션
- 배너
- 필터기능
- 커피챗 디자인
- 완성도 업

✨ Feat :  필터 연결, 애니메이션 추가

---

src/components/common/navigation-btn/NavigationBtn.jsx
src/components/common/new-btn/NewBtn.jsx
src/pages/info/InFo.jsx
src/pages/info/InfoSkill.jsx

🐛 Fix :  step3 기능 버그 개선

---

src/components/common/ToggleList.jsx
src/components/common/card/VideoCard.jsx
src/components/common/filters/Filters.jsx
src/pages/mainpage/Main.jsx

- 가격 콤마, 내맞춤탭 버그 수정, 필터 리턴값 동적으로 수정

🐛 Fix :  가격 콤마, 내맞춤탭 버그 수정, 필터 리턴값 동적으로 수정

---

src/api/api.js
src/components/common/BottomNav.jsx
src/components/common/filters/Filters.jsx
src/pages/coffeechat/Coffee.jsx
src/pages/mainpage/Main.jsx
src/pages/sign-in/KakaoRedirectPage.jsx

-백엔드 수정사항 반영
- api 호출 횟수 제한
- 로그인에 따른 ui
- ui 수정

🐛 Fix : 백엔드 수정사항 반영

---

src/components/common/BottomNav.jsx
src/pages/mainpage/Main copy.jsx
src/pages/mainpage/Main.jsx

- 검색 버그 수정, 하단네비 isLoggedInState 수정

🐛 Fix :  검색 버그 수정, 하단네비 isLoggedInState 수정

---

src/pages/mainpage/Main.jsx

🐛 Fix :  keydown 이벤트 한글 버그 해결

---

src/api/api.js
src/components/common/Pagenation.jsx
src/components/common/ToggleList.jsx
src/components/common/card/CoffeeChatCard.jsx
src/pages/MyCoffeeChat.jsx
src/pages/MyPage.jsx
src/pages/coffeechat/Coffee.jsx

- 커피챗 페이지네이션 구현, 커피챗 오류 수정, 마이페이지 디자인 수정

✨ Feat :  커피챗 페이지네이션 구현, 커피챗 오류 수정, 마이페이지 디자인 수정

---

package-lock.json
package.json
src/components/common/new-daypicker/NewDayPicker.jsx
src/pages/coffeechat/CoffeeOpen.jsx

- coffee chat, mypage 함수 분리
- 입력값 제한
closed: #75

[feat] date Picker 공통컴포넌트 수정(coffee chat, mypage)

---

src/pages/coffeechat/Coffee.jsx
src/pages/coffeechat/CoffeeOpen.jsx

- 커피챗 api 호출 제한, 페이지네이션 size변수 수정

🐛 Fix :  커피챗 api 호출 제한, 페이지네이션 size변수 수정

---

src/api/api.js
src/pages/coffeechat/Coffee.jsx

🐛 Fix :  page NAN 해결

---

src/api/api.js
src/components/common/card/VideoCard.jsx

- main page 영상 찜하기 api 연동(배포에서 확인필요)
closed: #99

[feat] 메인 동영상 api 연동 _#99

---

src/components/common/card/VideoCard.jsx
src/pages/PageStyles.js
src/pages/mainpage/CompanySection.jsx
src/pages/mainpage/Main.jsx
src/pages/mainpage/VideoSection.jsx

🐛 Fix :  좋아요 버튼 버그 수정

---

src/api/api.js
src/pages/FavoritesVideo.jsx
src/pages/MyCoffeeChat.jsx

- 마이페이지 커피챗 디자인 수정(페이지네이션, 데이터 없는 경우 글씨 안내)
- 마이페이지 영상찜화면 디자인 수정(페이지네이션, 데이터 없는 경우 글씨 안내)
closed: #119

[style] my page의 vedio 화면 및 커피챗 화면 디자인 수정 #119

---

src/App.jsx
src/pages/MyPage.jsx

- 마이페이지 접근시 에러 메세지 대신 로그인 화면으로 이동
closed: #119

[Feat] 로그인 접근권한 제어 오류 수정login authority #110

---

package-lock.json
package.json
src/components/common/card/CardStyle.js
src/components/common/new-daypicker/NewDayPicker.jsx
src/components/common/new-input/NewInput.jsx
src/components/common/total-input-form/TotalInputForm.jsx
src/pages/coffee-detail/Button.jsx
src/pages/coffee-detail/CoffeeDetail.jsx
src/pages/coffeechat/Coffee.jsx
src/pages/coffeechat/CoffeeOpen.jsx
src/pages/info/InfoStyles.js

✨ Feat : 커피챗 상세&메인 수정, 커피챗 공유 기능 구현

---

src/components/common/BottomNav.jsx

✨ Feat :  로그인 상태관리 변경

---

src/pages/FavoritesVideo.jsx

[fix] 마이페이지 영상찜 화면 페이지 0으로 픽스

---

src/api/api.js
src/pages/FavoritesVideo.jsx

[fix] 찜하기 안불러와지는 에러 수정완료

---

src/components/common/BottomNav.jsx

[Fix]로그인 유무에 따른 네비바 수정_login authority #110

---

src/api/api.js
src/pages/mypage/MyPage.jsx

[Fix]faq 데이터 연결 연동_login authority #110

---

src/pages/mypage/MyPage.jsx

[fix] 로그아웃 수정

---

src/api/api.js
src/pages/mypage/MyPage.jsx

- 주석처리 및 useEffect  실행순서 api 통신이전으로 변경

[fix] 로그아웃 통신 에러로 인한 임시로 에러 막음

---

src/App.jsx
src/pages/mypage/MyPage.jsx

- 로그인 상태값 useState로 변경
- 로그아웃 api 임시로 실행순서 뒤로 미룸

[Feat] 로그인 여부 상태값 업데이트 중  login authority #110

---

src/App.jsx
src/api/api.js
src/pages/coffeechat/Coffee.jsx
src/pages/mypage/MyPage.jsx

Develop_로그인 상태값 useState로 변경

---

src/components/common/card/VideoCard.jsx
src/index.js
src/pages/mainpage/Main.jsx

- 영상 좋아요 취소 api 통신 수정
closed: #110

[fix] 동영상 좋아요 취소시 api 연동 테스트

---

package-lock.json
package.json
public/index.html
src/App.jsx

- 리액트 헬멧 라이브러 설치
- 메타 태그 수정
closed: #150

[Feat]seo 메타 태그 수정_#150

---

src/components/common/card/CardStyle.js
src/components/common/card/CoffeeChatCard.jsx
src/components/common/card/VideoCard.jsx
src/components/common/new-daypicker/NewDayPicker.jsx
src/components/common/total-input-form/TotalInputForm.jsx
src/pages/coffee-detail/HostInfoWithViewcount.jsx
src/pages/coffeechat/Coffee.jsx
src/pages/coffeechat/CoffeeBanner.jsx
src/pages/coffeechat/CoffeeOpen.jsx
src/pages/coffeechat/FiltersAndButton.jsx
src/pages/info/InFo.jsx
src/pages/info/InFoBasic.jsx
src/pages/mainpage/Main.jsx
src/pages/mypage/FavoritesVideo.jsx
src/pages/sign-in/LoginBtn.jsx
src/pages/sign-in/RedirectPage copy.jsx
src/pages/sign-in/RedirectPage.jsx
src/recoil/atoms.jsx

- CoffeeOpen 등록 성공 시 버튼 비활
- CoffeeChatCard 종료 처리
- job 값 자동화
- 커피챗 관련 파일들 리팩토링

✨ Feat :  CoffeeOpen 등록 성공 시 버튼 비활, CoffeeChatCard 종료 처리, job 값 자동화

---

src/components/common/BottomNav.jsx
src/components/common/Pagenation.jsx
src/components/common/card/CoffeeChatCard.jsx
src/components/common/card/VideoCard.jsx
src/components/common/new-daypicker/NewDayPicker.jsx
src/pages/mypage/FavoritesVideo.jsx
src/pages/mypage/MyCoffeeChat.jsx
src/pages/mypage/MyPage.jsx

> #153 
1. 데이피커 유효성 검사 추가
2. 커피챗, 찜화면 레이아웃 수정
3. 마이페이지 하위경로 네비바 마이페이지로 활성화하도록 수정
4. 찜화면 좋아요 취소시 리렌더링 발생시켜 해당 강의 안보이게 수정

Feat/my page/fix #153

---

package.json
src/api/api.js
src/components/common/new-daypicker/NewDayPicker.jsx
src/pages/info/Done.jsx
src/pages/info/SignupFail.jsx
src/pages/mainpage/Main.jsx
src/pages/sign-in/RedirectPage.jsx
src/recoil/atoms.jsx

close #167 
회원가입 시 DayPicker를 통해 생일을 선택하면 값을 가져오지 못하는 문제가 발생했었습니다.
이에 문제가 되는 부분을 발견, `NewDayPicker.jsx` 파일의 날짜 포매터가 누락되는 문제가 있어 수정했습니다.
(사진 찍어둘걸 그랬네요..ㅠㅠ 지금 재 가입이 안되네요 🤣🤣)
```jsx
const handleDateChange = (newDate) => {
if (typeof newDate === 'string') {
newDate = parseISO(newDate); // 이부분..!
}
if (newDate < now) {
onChange(newDate);
}
```
현재는 잘 받아와집니다.
해당 내용은 지원님과 함께 진행했으니 자세한 설명은 생략하도록 하겠씁니다..!!

🐛 Fix : DayPicker value값 코드 수정 #167

---

src/api/api.js
src/pages/mainpage/Main.jsx
src/pages/mainpage/StickyTabSection.jsx
src/pages/mainpage/useAuth.jsx
src/pages/mainpage/useLoadData.jsx

♻️ Refactor : 메인페이지 기능 별로 분리

---

src/pages/mainpage/useLoadData.jsx

> ex) #183 
>
준규님과 아까 회의실에서 논의한 부분입니다!
기능이 동작되도록 하고 useEffect 하나로 통일하였습니다

🐛 Fix : 메인페이지 빈 검색어 오류 수정

---

src/App.jsx
src/api/api.js

> #191 
> 준규님께서 말씀해주신 오류 확인해봤습니다
```jsx
export async function Authentication() {
try {
const res = await instance.get("/api/v1/authenticate");
return res.data.data;
} catch (error) {
console.error("user login state", error);
throw error;
}
}
```
이부분 백엔드에서 수정해주신대로 기존 pr 에서 수정했지만,,ㅠ 머지 과정에서 생긴 api.js 충돌을 해결하다가 제가 인덱싱 해놓은 부분이 실수로 삭제된 것 같더라고요ㅜ😂 그래서 다시 해결했습니다! 
확인부탁드려요~

🚑️ Hotfix:  로그인 판별 api 인덱싱 수정

---

src/App.jsx
src/components/common/BottomNav.jsx
src/components/common/new-input/NewInput.jsx
src/pages/jd-all/JDBanner.jsx
src/pages/jd-all/JDComponent.jsx
src/pages/jd-all/index.jsx
src/pages/mainpage/CompanySection.jsx
src/pages/sign-in/LoginBtn.jsx
src/pages/sign-in/SignIn.jsx

close #198 
close #216 
close #213 
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

🐛 Fix : UI 수정 및 로그인 버튼 문구 변경 QA 반영

---

src/components/common/new-daypicker/NewDayPicker.jsx
src/pages/info/InFoBasic.jsx

> ex) #220 
> 
- 위처럼 들어가던 생일 데이터가 아래처럼 들어가도록 포맷팅 했습니다
회원가입 테스트 부탁드려요!

🐛 Fix :회원가입 생일 입력 포맷팅

---

src/api/api.js
src/pages/coffee-detail/CoffeeChatInfo.jsx
src/pages/coffee-detail/CoffeeDetail.jsx
src/pages/coffeechat/CoffeeOpen.jsx
src/pages/jd-detail/CategoryTab.jsx

> ex) #220 
>
커피챗 상세 content 줄바꿈 구분하도록 하였습니다
-   줄바꿈 기호가 포함되어 내려오는 데이터에서 `₩n` 를 `</br>` 로 변경

🐛 Fix :  커피챗 상세 content 줄바꿈 구분

---

src/pages/coffeechat/CoffeeOpen.jsx

> ex) #220 
> 
- 커피챗 생성 후 해당 커피챗의 상세 페이지로 이동시킬 때 생기는 이슈를 해결 중입니다
- 변경된 점 : id 값을 Number 형태로 변환
- 로컬환경은 정상작동하지만 배포환경에서만 발생하는 이슈라 pr 머지 후 확인 가능할 것 같습니다
-

🐛 Fix : id 파라미터 number 타입으로 변경

---

src/App.jsx
src/api/api.js
src/components/common/BottomNav.jsx
src/pages/coffeechat/CoffeeOpen.jsx
src/pages/coffeechat/FiltersAndButton.jsx
src/pages/mainpage/useAuth.jsx
src/recoil/atoms.jsx

> 
> 
- 변경된 백엔드 api에 따라 로그인 성공 유무 필드명과 커피챗 아이디 필드명이 변경되었습니다

✨ Feat : 필드명이 변경

---

src/pages/mypage/MyCoffeeChat.jsx

> ex)
> 
- 이전 pr에서 마이페이지의 커피챗 jobBadge 색상을 변경하였는데 내가 오픈한 커피챗에만 적용되고 내가 신청한 커피챗에는 적용되지 않아서 이부분 수정하였습니다

💄 Design: 내가 오픈한 커피챗 디자인 수정

---

src/api/api.js
src/components/common/swipe/SwipJobSkill.jsx
src/pages/mypage/InfoEdit.jsx

close #246 
```js
/* 수정 전 */
// 마이페이지 수정 화면이 그려지면서 이부분이 아주 잠깐동안 혼자 빈 값을 보내더라구요..
const res = await getSkillsOnJD(jobId); // 서버개발자 or 프론트개발자
/* 수정 후 */
// 그래서 빈값인 경우에는 무조건적으로 ID값을 2가 전송되도록 했습니다. (응급처치 수준이지만요..!)
const res = await getSkillsOnJD(jobId ? jobId : 2); // 이렇게 처리해도 나중에 화면 불러오는데는 큰 문제가 없더라구요!
```

🐛 Fix : 회원정보수정 api url 수정

---

src/components/common/navigation-btn/NavigationBtnStyles.js
src/pages/jd-all/JDComponent.jsx
src/pages/mypage/InfoEdit.jsx
src/pages/mypage/Withdrawal.jsx

close #204 
추후 ui 스타일 수정이 이루어 질 예정입니다!

♻️ Refactor : 회원 탈퇴 방식 수정

---

src/components/common/card/VideoCard/index.jsx
src/pages/jd-detail/CategoryTab.jsx

🐛 Fix : 인프런 강의 수강자 수 toLocaleString 추가 

---

src/pages/PageStyles.js
src/pages/sign-in/LoginBtn.jsx

💄 Design : 로그인 버튼 pointer 속성 추가

---

.github/workflows/Build_React_App.yml

🐛 Fix : build yml 수정

---

.github/workflows/Build_React_App.yml
src/api/api.js

🚨 Hotfix : 서버 환경에서 환경변수를 참조하지 못하는 이슈발견 및 수정

---

src/api/api.js

🐛 Fix : 이전 api코드로 원상복귀

---

.github/workflows/Build_React_App.yml
src/api/api.js
src/pages/sign-in/LoginBtn.jsx

🚨 Fix : 환경변수 변경

---

.github/workflows/Build_React_App.yml
src/pages/mainpage/Main.jsx

🚨 Hotfix : 재 배포

---

public/index.html
src/App.jsx

📦 Chore : meta 및 title 태그 변경

---

.github/workflows/Build_React_App.yml

📦 Chore : 누락사항 변경

---

.github/workflows/Build_React_App.yml

📦 Chore : 진짜 마지막 yml 수정

---

.github/workflows/Build_React_App.yml

📦 Chore : 제발..

---

src/pages/mainpage/useLoadData.jsx

-
API 무한요청 수정작업 이후 간헐적으로 선택된 키워드가 api호출을 하지 않는 현상을 해결했습니다.

🐛 Fix : 키워드 반영되지 않는 이슈 해결

---

src/api/api.js
src/components/common/card/CoffeeChatCard/CardBody.jsx
src/components/common/card/CoffeeChatCard/index.jsx
src/pages/mypage/MyCoffeeChat.jsx

> 
>
- 커피챗 취소 기능을 구현했어야 하는데 삭제 기능을 구현해놓아서 ,, 취소 api 로 변경하였습니다 😀

🐛 Fix : 커피챗  삭제 -> 취소로 변경

---

src/components/common/BottomNav.jsx
src/constants/headerProps.js
src/pages/jd-all/index.jsx
src/pages/mypage/Withdrawal.jsx

🚨 Hotfix : JD 목록페이지에 들어가지 못하던 문제 해결

---

src/pages/coffeechats/coffeechat-list/FiltersAndButton.jsx

🚑️ Hotfix:  폴더명 변경

---

package-lock.json
package.json
src/api/api.js
src/components/common/card/VideoCard/index.jsx
src/pages/coffeechats/coffeechat-list/index.jsx
src/pages/coffeechats/create-coffeechats/index.jsx
src/pages/coffeechats/detail-coffeechats/CoffeeChatInfo.jsx
src/pages/info/InFo.jsx
src/pages/mypage/FavoritesVideo.jsx
src/pages/mypage/InfoEdit.jsx

> close #271 
> 
- 처음 페이지 값 = 0으로 api 요청하도록 `<pagenationComponent />` 사용하여 페이징 처리하였습니다
- 저번에 이슈 처리를 하며 padding 값이 없어졌었는데 다시 추가하였습니다
- 기존에는 pop animation이 작동을 하지 않았습니다
- 클릭과 동시에 pop 이 되도록 수정하였습니다

🐛 Fix : 마이페이지 페이지네이션 api 연동 & divider padding 추가

---

src/components/common/search-bar/HeaderWithSearchBar.jsx

> 
> 
아래 영상은 문제의 상황을 녹화한 것입니다
영상과 같이 검색어를 **입력했다가 -> 삭제해도** 기존 검색어가 남아있는 버그를 해결하였습니다
https://github.com/Kernel360/f1-JDON-Frontend/assets/103630185/f59428a9-d53b-47bc-86e5-e2679c93900e
검색어

🚑️ Hotfix:  검색어 유지 버그 해결

---

src/components/coffeechats/List/ui/InfoItemWrapper.jsx
src/components/coffeechats/List/ui/UserInfo.jsx
src/components/coffeechats/Update/ui/UpdateCoffeeChatForm.jsx
src/components/coffeechats/create/ui/CreateCoffeeChatForm.jsx
src/components/coffeechats/detail/ui/CoffeeDetailButtons.jsx
src/hooks/useCoffeeForm.jsx
src/pages/CoffeeCreatePage.jsx
src/pages/CoffeeDetailPage.jsx
src/pages/CoffeeListPage.jsx

> ex) 
> 
- 빌드 오류 수정 중입니다 
- 파일명 변경
- 새로운 브랜치 생성

🔨 Modify: 빌드 오류 수정

---

src/components/coffeechats/detail-coffeechats/queryHooks/useApplyForCoffeeChat.jsx

> close #358 
> 
에러인 경우 `alert`으로 에러 메세지를 보여줍니다
```jsx
const { mutate, isLoading, error } = useMutation(
(applyCoffeeValue) => applyCoffeechat(id, applyCoffeeValue),
{
onSuccess: () => {
alert('신청이 완료되었습니다.');
},
onError: (error) => {
alert(error.response.data.message);
},
},
```

🐛 Fix :  커피챗 신청하기 400 에러 핸들링

---

src/pages/jd-detail/CategoryTab.jsx

🚑️ Hotfix:  찜 로그인 상태관리 수정
